# Generated by Django 6.0 on 2026-01-03 20:43

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='booking_deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last time users can book this tour'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 3, 20, 43, 40, 72284, tzinfo=datetime.timezone.utc), help_text='When the tour starts'),
            preserve_default=False,
        ),
    ]
