# Generated by Django 6.0 on 2026-01-07 19:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tourreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Short description under title', max_length=255)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='tours.tour')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('tour', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='TourDayActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('is_included', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tours.tourday')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
