# Generated by Django 6.0 on 2026-01-07 20:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tourday_tourdayactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourInclusion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('is_included', models.BooleanField(default=True, help_text='Checked = Included, Unchecked = Not Included')),
                ('order', models.PositiveIntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='tours.tour')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
