# Generated by Django 6.0 on 2026-01-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_stay_transport_stayreview_transportreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stay',
            name='stay_type',
        ),
        migrations.AddField(
            model_name='stay',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
