# Generated by Django 6.0 on 2026-01-07 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_remove_stay_stay_type_stay_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='stay',
            field=models.ForeignKey(default='4fa042cd-a947-4270-ae4a-255a35b04f56', on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='tours.stay'),
            preserve_default=False,
        ),
    ]
