# Generated by Django 6.0 on 2026-01-07 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_tour_stay'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='transport',
            field=models.ForeignKey(default='73ae01c6-a27a-4224-ad33-514d1024840c', on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='tours.transport'),
            preserve_default=False,
        ),
    ]
