# Generated by Django 6.0 on 2026-01-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_tourbooking_accepted_terms_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourbooking',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='tourbooking',
            name='refunded_at',
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='booking_reference',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='draft', max_length=20),
        ),
    ]
